#!/bin/bash
# This file is auto generated by IDV setup.sh file.
VGPU1=74475dba-ffa9-11ea-93bd-cb8e3fe2d1c9
VGPU2=74481d22-ffa9-11ea-a6a2-4789798d72bc
VGPU3=7448d820-ffa9-11ea-b265-2b1ede9857dc
echo "0x080402" > /sys/class/drm/card0/gvt_disp_ports_mask
echo "VGPU1" > /sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create
echo "VGPU2" > /sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create
echo "VGPU3" > /sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create
