#!/bin/bash
# This file is auto generated by IDV setup.sh file.
/usr/local/bin/qemu-system-x86_64 \
-m 4096 -smp 1 -M q35 \
-enable-kvm \
-name  android-vgpu2 \
-boot d \
-cdrom /home/giga/test/idv/iso/android.iso \
-drive file=./vm/disk/android-vgpu2.qcow2 \
-bios ./vm/fw/bios.bin \
-cpu host -usb -device usb-tablet \
-vga cirrus \
-k en-us \
-vnc :0
