#!/bin/bash
# This file is auto generated by IDV setup.sh file.
/usr/local/bin/qemu-system-x86_64 \
-m 4096 -smp 1 -M q35 \
-enable-kvm \
-name  ubuntu-vgpu3 \
-boot d \
-cdrom /home/giga/test/idv/iso/ubuntu.iso \
-drive file=./vm/disk/ubuntu-vgpu3.qcow2 \
-bios ./vm/fw/bios.bin \
-cpu host -usb -device usb-tablet \
-vga cirrus \
-k en-us \
-vnc :0
