#!/bin/bash -x
# This file is auto generated by IDV setup.sh file.
/usr/bin/qemu-system-x86_64 \
-m 4096 -smp 1 -M q35 \
-enable-kvm \
-name  android-vgpu1 \
-hda ./vm/disk/android-vgpu1.qcow2 \
-bios ./vm/fw/bios.bin \
-cpu host -usb -device usb-tablet \
-vga none \
-k en-us \
-vnc :0 \
-cpu host -usb -device usb-tablet \
-device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/74475dba-ffa9-11ea-93bd-cb8e3fe2d1c9,display=off,x-igd-opregion=on
